apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jcon-app-svc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: eldermoraes/jcon-app:1.0-SNAPSHOT